accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import admin_blog
from django.contrib.auth import views as auth_views

# Tus otras URLs...



urlpatterns = [
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset_form.html'
    ), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html',
        success_url='/signin/'
    ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'
    ), name='password_reset_complete'),

    path('', views.index, name='index'),  # Asegúrate de que 'views.index' es tu función de vista que maneja la búsqueda

    path('signup/', views.signup_user, name='signup_user'),
    path('signup_comp/', views.signup_comp, name='signup_comp'),
    path('signup_admin/', views.signup_admin, name='signup_admin'),
    path('signout/', views.signout, name='logout'),
    path('signin/', views.signin, name='signin'),
    path('signin_admin/', views.signin_admin, name='signin_admin'),
    path('manage_companies/', views.manage_companies, name='manage_companies'),
    path('company_details/<int:company_id>/', views.company_details, name='company_details'),
    path('activate_company/<int:company_id>/', views.activate_company, name='activate_company'),
    path('inactivate_company/<int:company_id>/', views.inactivate_company, name='inactivate_company'),
    path('create_job_post/', views.create_job_post, name='create_job_post'),
    path('my_job_list/', views.my_job_list, name='my_job_list'),
    path('delete_job_post/<int:job_id>/', views.delete_job_post, name='delete_job_post'),
    path('toggle_job_post_status/<int:job_id>/', views.toggle_job_post_status, name='toggle_job_post_status'),
    path('my_profile/', views.my_profile, name='my_profile'),
    path('upload-cv/', views.upload_cv, name='upload_cv'),
    path('admin_blog/', views.admin_blog, name='admin_blog'),
    path('faqs/', views.faqs, name='faqs'),
    path('ruta-para-actualizar-datos/', views.update_user_data, name='update_user_data'),
    path('upload-profile-picture/', views.upload_profile_picture, name='upload_profile_picture'),
    path('ruta-para-obtener-sectores/', views.load_sectors, name='load_sectors'),
    path('job_details/<int:job_id>/', views.job_details, name='job_details'),
    path('edit-job/<int:job_id>/', views.edit_job_post, name='edit_job_post'),
    path('apply_for_job/<int:job_id>/', views.apply_for_job, name='apply_for_job'),
    path('my_applications/', views.my_applications, name='my_applications'),
    path('jobs/<int:job_id>/applicants/', views.view_applicants, name='view_applicants'),
    path('questions/delete/<int:question_id>/', views.delete_question, name='delete_question'),
    path('activate/<uidb64>/<token>/', views.activate_account, name='activate_account'),
    path('activation_valid/', views.activation_valid, name='activation_valid'),
    path('resend_activation_email/<uidb64>/', views.resend_activation_email, name='resend_activation_email'),
    path('activation_valid_admin/', views.activation_valid_admin, name='activation_valid_admin'),
    path('admin_faq/', views.admin_faq, name='admin_faq'),
    path('admin_questions/', views.admin_questions, name='admin_questions'),
    path('privacy_policy/', views.privacy_policy_view, name='privacy_policy'),
    path('terms_and_conditions/', views.terms_and_conditions_view, name='terms_and_conditions'),
    path('about_me/', views.about_me_view, name='about_me'),
    path('contact/', views.contact_view, name='contact'),
    path('agendanos/', views.agendanos_view, name='agendanos'),
    path('team/', views.team_view, name='team'),
    path('contact/success/', views.contact_success, name='contact_success'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

legame/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('i18n/', include('django.conf.urls.i18n')),

] + i18n_patterns(
    # Incluye tus URLs que necesitan traducción aquí
)

accounts/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from django.core.validators import URLValidator


CANTIDAD_EMPLEADOS_CHOICES = [
    ('1-10', 'Entre 1 y 10'),
    ('11-50', 'Entre 11 y 50'),
    ('51-150', 'Entre 51 y 150'),
    ('151-300', 'Entre 151 y 300'),
    ('301-500', 'Entre 301 y 500'),
    ('501-1000', 'Entre 501 y 1000'),
    ('1001-más', 'Más de 1000'),
]

CATEGORY_CHOICES = [
        ('Full-time', 'Full-time'),
        ('Part-time', 'Part-time'),
    ]

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank=True)  # Nuevo campo para el nombre
    lastname = models.CharField(max_length=100, blank=True)  # Nuevo campo para el apellido
    email = models.EmailField(unique=True)  # Asegura que el email sea único
    phone_number = PhoneNumberField(blank=True, help_text='Número de teléfono con prefijo internacional')
    bio = models.TextField(blank=True)
    cv = models.FileField(upload_to='cvs/', null=True, blank=True)
    profile_picture = models.ImageField(upload_to='profile_pics/', null=True, blank=True)
    email_confirmed = models.BooleanField(default=False)
# Nuevos campos para enlaces de redes sociales
    website = models.URLField(blank=True, null=True)
    def validate_social_url(value):
        validator = URLValidator()
        try:
            validator(value)
        except ValidationError:
            raise ValidationError("La URL no es válida")

    github = models.URLField(blank=True, null=True, validators=[validate_social_url])
    twitter = models.URLField(blank=True, null=True, validators=[validate_social_url])
    instagram = models.URLField(blank=True, null=True, validators=[validate_social_url])
    facebook = models.URLField(blank=True, null=True, validators=[validate_social_url])
    linkedin = models.URLField(blank=True, null=True, validators=[validate_social_url])
    
    GENDER_CHOICES = [
        ('Masculino', 'Masculino'),
        ('Femenino', 'Femenino'),
        ('No Binario', 'No Binario'),
    ]
    genero = models.CharField(max_length=12, choices=GENDER_CHOICES, blank=True)
    DOCUMENT_TYPE_CHOICES = [
        ('DNI', 'DNI'),
        ('CI', 'CI'),
        ('LE', 'LE'),
        ('LC', 'LC'),
        ('PASSPORT', 'Pasaporte'),
    ]
    document_type = models.CharField(max_length=10, choices=DOCUMENT_TYPE_CHOICES, blank=True)
    document_number = models.CharField(max_length=20, blank=True, unique=True)  # Asegura que la documentación sea única
    User.add_to_class('email_confirmed', models.BooleanField(default=False))

    
    def __str__(self):
        return f'{self.name} {self.lastname} - {self.user.username}'



class Company(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    company_name = models.CharField(max_length=100)
    address = models.CharField(max_length=255)
    contact_email = models.EmailField()
    phone_number = PhoneNumberField(blank=True, help_text='Número de teléfono con prefijo internacional')
    province_name = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=100, blank=True)
    sector = models.CharField(max_length=100, blank=True, verbose_name='Categoría')
    razón_social = models.CharField(max_length=100)  # Nuevo campo para la razón social
    cantidad_empleados = models.CharField(max_length=50, choices=CANTIDAD_EMPLEADOS_CHOICES)
    cuit = models.CharField(max_length=13, unique=True)  # Incluye los guiones en la longitud máxim
    STATUS_CHOICES = (
        ('active', 'Activa'),
        ('inactive', 'Inactiva'),
    )
    status = models.CharField(max_length=8, choices=STATUS_CHOICES, default='inactive')
    region_it = models.CharField("Región (Italia)", max_length=100, blank=True, null=True)
    provincia_it = models.CharField("Provincia (Italia)", max_length=100, blank=True, null=True)
    comuna_it = models.CharField("Comuna (Italia)", max_length=100, blank=True, null=True)
    country = models.CharField(max_length=2, choices=[('AR', 'Argentina'), ('IT', 'Italia')], default='AR')
    email_confirmed = models.BooleanField(default=False)
# Nuevos campos para enlaces de redes sociales
    website = models.URLField(blank=True, null=True)
    def validate_social_url(value):
        validator = URLValidator()
        try:
            validator(value)
        except ValidationError:
            raise ValidationError("La URL no es válida")

    github = models.URLField(blank=True, null=True, validators=[validate_social_url])
    twitter = models.URLField(blank=True, null=True, validators=[validate_social_url])
    instagram = models.URLField(blank=True, null=True, validators=[validate_social_url])
    facebook = models.URLField(blank=True, null=True, validators=[validate_social_url])
    linkedin = models.URLField(blank=True, null=True, validators=[validate_social_url])

    def __str__(self):
        return self.company_name


class AdminUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Campos adicionales específicos para administradores, si son necesarios
    email = models.EmailField(unique=True)  # Asegura que el email sea único
    email_confirmed = models.BooleanField(default=False)
# Nuevos campos para enlaces de redes sociales
    website = models.URLField(blank=True, null=True)
    def validate_social_url(value):
        validator = URLValidator()
        try:
            validator(value)
        except ValidationError:
            raise ValidationError("La URL no es válida")

    github = models.URLField(blank=True, null=True, validators=[validate_social_url])
    twitter = models.URLField(blank=True, null=True, validators=[validate_social_url])
    instagram = models.URLField(blank=True, null=True, validators=[validate_social_url])
    facebook = models.URLField(blank=True, null=True, validators=[validate_social_url])
    linkedin = models.URLField(blank=True, null=True, validators=[validate_social_url])
    
    def __str__(self):
        return self.user.username

#Pantalla para publicaciones de empresas

class JobPost(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    sector  = models.CharField(max_length=50)
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default='full-time')
    country = models.CharField(max_length=2, choices=[('AR', 'Argentina'), ('IT', 'Italia')], default='AR')
    province_name = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    descripcion = models.TextField(blank=True)  # Campo nuevo para la descripción
    application_limit = models.PositiveIntegerField(default=10)  # Un valor por defecto de 10
    expiration_date = models.DateField("Fecha de vencimiento", default=timezone.now)
    address = models.CharField(max_length=255, blank=True)  # Nuevo campo para la dirección
    region_it = models.CharField("Región (Italia)", max_length=100, blank=True, null=True)
    provincia_it = models.CharField("Provincia (Italia)", max_length=100, blank=True, null=True)
    comuna_it = models.CharField("Comuna (Italia)", max_length=100, blank=True, null=True)
    
    STATUS_CHOICES = (
        ('active', 'Activa'),
        ('inactive', 'Inactiva'),
    )
    status = models.CharField(max_length=8, choices=STATUS_CHOICES, default='active')
    def __str__(self):
        return self.title

# models.py


class BlogEntry(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    updated_at = models.DateTimeField(auto_now=True)
    def get_translation(self, language_code):
        return self.translations.filter(language=language_code).first()
    def __str__(self):
        return self.title

class BlogEntryTranslation(models.Model):
    blog_entry = models.ForeignKey(BlogEntry, on_delete=models.CASCADE, related_name='translations')
    language = models.CharField(max_length=2, choices=[('es', 'Spanish'), ('it', 'Italian')])
    title = models.CharField(max_length=200)
    content = models.TextField()

    class Meta:
        unique_together = ('blog_entry', 'language')

    def __str__(self):
        return f'{self.language} translation of {self.blog_entry.title}'

    
    
class Application(models.Model):
    job = models.ForeignKey(JobPost, on_delete=models.CASCADE, related_name='applications')
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='applications')
    applied_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user_profile} se ha postulado a {self.job}'
    
    
    
class UserSession(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    session_key = models.CharField(max_length=40)
    device_identifier = models.CharField(max_length=255) # Identificador del dispositivo
    created_at = models.DateTimeField(auto_now_add=True)
    
    
class FAQ(models.Model):
    title = models.CharField(max_length=200)  # Neutral title
    content = models.TextField()  # Neutral content

    def __str__(self):
        return self.title

    def get_translation(self, language_code):
        # Lógica para obtener la traducción basada en el código de idioma
        if language_code == 'es':
            return self.title_es, self.content_es
        elif language_code == 'it':
            return self.title_it, self.content_it
        else:
            # Manejo de idioma predeterminado o error

accounts/templates/jobs/create_job_post.html
{% extends "base.html" %}
{% load static widget_tweaks %}
{% load i18n %}
{% block content %}
<link href="{% static 'stylesfooter.css' %}" rel="stylesheet">
<link href="{% static 'stylescomp.css' %}" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
    <div class="contact__wrapper shadow-lg mt-n9">
        <div class="row no-gutters">
            <div class="col-lg-5 contact-info__wrapper gradient-brand-color p-5 order-lg-2">
                <h3>{% trans "CREATE_JOB" %}</h3>
            </div>
    
            <div class="col-lg-7 contact-form__wrapper p-5 order-lg-1">
                <form method="post" class="needs-validation" novalidate>
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-sm-6 mb-3">
                            <div class="form-group">
                                <label for="id_country">{% trans "COUNTRY" %}:</label>
                            <select name="country" class="form-control" id="id_country" required>
                                <option value="AR">Argentina</option>
                                <option value="IT">Italia</option>
                            </select>
                            </div>
                        </div>
                        <div id="argentinian-fields">

                        <div class="col-sm-6 mb-3">
                            <div class="form-group">
                                <label for="id_province">Provincia/Estado:</label>
                                <select name="province_name" id="province" class="form-control" onchange="updateCities()">
                                    <option value="">Selecciona una provincia</option>
                                    {% for province in provinces %}
                                        <option value="{{ province.id }}">{{ province.nombre }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
    
                        <div class="col-sm-6 mb-3">
                            <div class="form-group">
                                <label for="id_city">Ciudad/Localidad:</label>
                                <select name="city" id="city" class="form-control">
                                    <option value="">Primero selecciona una provincia</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div id="italy-fields" style="display: none;">

                        <div class="col-sm-6 mb-3">
                            <div class="form-group">
                        <label for="select-region">Regione:</label>
                        <select id="select-region" name="region_it" class="form-control" onchange="cargarProvincias()">
                            <option value="">Seleziona una regione</option>
                        </select>
                    </div>
                </div>
                        <div class="col-sm-6 mb-3">
                            <div class="form-group">
                        <label for="select-provincia" >Provincia:</label>
                        <select id="select-provincia" name="provincia_it" class="form-control" onchange="cargarComunas()">
                            <option value="">Seleziona una provincia</option>
                        </select>
                    </div>
                </div>
                        <div class="col-sm-6 mb-3">
                            <div class="form-group">
                        <label for="select-comuna">Comune:</label>
                        <select id="select-comuna" name="comuna_it" class="form-control">
                            <option value="">Seleziona un comune</option>
                        </select>
                        </div>
                    </div>
                </div>
                        <div class="col-sm-6 mb-3">
                            <div class="form-group">
                                <label for="id_sector">{% trans "SECTOR" %}:</label>
                                <select name="sector" id="id_sector" class="form-control" required>
                                {% for value, text in form.fields.sector.choices %}
                                <option value="{{ value }}">{{ text }}</option>
                                {% endfor %}
                            </select>
                            </div>
                        </div>

                        <div class="col-sm-6 mb-3">
                            <div class="form-group">
                                <label for="id_category">{% trans "CATEGORIA" %}:</label>
                            <select name="category" id="id_category" class="form-control" required>
                                {% for value, text in form.fields.category.choices %}
                                <option value="{{ value }}">{{ text }}</option>
                                {% endfor %}
                            </select>
                            </div>
                        </div>
                        <div class="col-sm-6 mb-3">
                            <label for="id_expiration_date">{% trans "FECHA_VENCIMIENTO" %}:</label>
                            {{ form.expiration_date|add_class:"form-control" }}
                            {% if form.expiration_date.errors %}
                                {% for error in form.expiration_date.errors %}
                                    <div class="invalid-feedback">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div class="col-sm-6 mb-3">
                            <label for="id_application_limit">{% trans "LIMIT_POST" %}:</label>
                            <input type="number" name="application_limit" id="id_application_limit" class="form-control" value="{{ form.application_limit.value|default_if_none:10 }}" min="1" required>
                            {% if form.application_limit.errors %}
                                {% for error in form.application_limit.errors %}
                                    <div class="invalid-feedback">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div class="col-sm-6 mb-3">
                            <label for="id_address">{% trans "ADRESS" %}:</label>
                            <input type="text" name="address" id="id_address" class="form-control" value="{{ form.address.value|default_if_none:'' }}" required>
                            {% if form.address.errors %}
                                {% for error in form.address.errors %}
                                    <div class="invalid-feedback">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div class="mb-3">
                            <label for="id_title">{% trans "TITLE_JOB" %}:</label>
                            <input type="text" name="title" id="id_title" class="form-control" value="{{ form.title.value|default_if_none:'' }}" required>
                            {% if form.title.errors %}
                                {% for error in form.title.errors %}
                                    <div class="invalid-feedback">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div class="col-sm-12 mb-3">
                            <div class="form-group">
                                <label for="id_descripcion" required>{% trans "DESCRIP_JOB" %}:</label>
                            {{ form.descripcion|add_class:"form-control" }}
                        </div>
                        <br>
                        <button type="submit" class="btn btn-primary">{% trans "PUBLICAR_JOB" %}</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <!-- End Contact Form Wrapper -->
    
        </div>
    </div>
</div>

<script>
    var provinceToCities = {{ province_to_cities_map|safe }};
  
    function updateCities() {
        console.log("Actualizando ciudades...");
  
        var provinceSelect = document.getElementById('province');
        var citySelect = document.getElementById('city');
        var selectedProvinceId = provinceSelect.value;
  
        console.log("Provincia seleccionada: " + selectedProvinceId);
  
        citySelect.innerHTML = '';
  
        // Comprobar que el mapeo contiene la provincia seleccionada
        console.log(provinceToCities);
        if (!provinceToCities[selectedProvinceId]) {
            console.log("No se encontraron ciudades para la provincia con ID: " + selectedProvinceId);
        }
  
        var cities = provinceToCities[selectedProvinceId] || [];
  
        console.log("Ciudades encontradas: ", cities);
  
        cities.forEach(function(cityName) {
            console.log("Añadiendo ciudad: " + cityName);
            var option = document.createElement('option');
            option.value = cityName;
            option.textContent = cityName;
            citySelect.appendChild(option);
        });
    }
// Funciones similares para cargar provincias y comunas basadas en la región seleccionada
// ...
  // Función que se ejecuta al cargar la página
  document.addEventListener('DOMContentLoaded', function() {
            cargarRegiones();
        });

        // Carga las regiones desde el archivo JSON
        function cargarRegiones() {
            fetch('/static/accounts/italia/italia.json') // Modifica esta ruta al archivo JSON
                .then(response => response.json())
                .then(data => {
                    const selectRegion = document.getElementById('select-region');
                    console.log(selectRegion)
                    data.regioni.forEach(region => {
                        let option = document.createElement('option');
                        option.value = region.nome;
                        option.textContent = region.nome;
                        selectRegion.appendChild(option);
                    });
                });
        }

        // Carga las provincias según la región seleccionada
        function cargarProvincias() {
            const regionSeleccionada = document.getElementById('select-region').value;
            fetch('/static/accounts/italia/italia.json') // Modifica esta ruta al archivo JSON
                .then(response => response.json())
                .then(data => {
                    const selectProvincia = document.getElementById('select-provincia');
                    selectProvincia.innerHTML = ''; // Limpiar provincias anteriores
                    data.regioni.forEach(region => {
                        if (region.nome === regionSeleccionada) {
                            region.province.forEach(provincia => {
                                let option = document.createElement('option');
                                option.value = provincia.nome;
                                option.textContent = provincia.nome;
                                selectProvincia.appendChild(option);
                            });
                        }
                    });
                });
        }

        // Carga las comunas según la provincia seleccionada
        function cargarComunas() {
            const provinciaSeleccionada = document.getElementById('select-provincia').value;
            fetch('/static/accounts/italia/italia.json') // Modifica esta ruta al archivo JSON
                .then(response => response.json())
                .then(data => {
                    const selectComuna = document.getElementById('select-comuna');
                    selectComuna.innerHTML = ''; // Limpiar comunas anteriores
                    data.regioni.forEach(region => {
                        region.province.forEach(provincia => {
                            if (provincia.nome === provinciaSeleccionada) {
                                provincia.comuni.forEach(comuna => {
                                    let option = document.createElement('option');
                                    option.value = comuna.nome;
                                    option.textContent = comuna.nome;
                                    selectComuna.appendChild(option);
                                });
                            }
                        });
                    });
                });
        }
        
        document.getElementById('id_country').addEventListener('change', function() {
    var country = this.value;
    var italianFields = document.getElementById('italy-fields');
    var argentinianFields = document.getElementById('argentinian-fields');

    if (country === 'IT') {
        italianFields.style.display = 'block';
        argentinianFields.style.display = 'none';
    } else {
        italianFields.style.display = 'none';
        argentinianFields.style.display = 'block';
    }
});
  </script>
  
{% endblock %}

accounts/templates/jobs/job_details.html
{% extends "base.html" %}
{% load static %}
{% load tz %}
{% load i18n %}
{% block content %}
<link href="{% static 'stylesfooter.css' %}" rel="stylesheet">
<link href="{% static 'styleslistjob.css' %}" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.5.5/css/simple-line-icons.min.css" integrity="sha512-QKC1UZ/ZHNgFzVKSAhV5v5j73eeL9EEN289eKAEFaAjgAiobVAnVv/AGuPbXsKl1dNoel3kNr6PYnSiTzVVBCw==" crossorigin="anonymous" />
{% now "Y-m-d" as today %} <!-- Captura la fecha actual en una variable llamada "today" -->

<section>
  <div class="container">
    <div class="row mt-60">
      <div class="col-12">
        <div class="service-block4 h-100">
          <div class="service-icon">
            <i class="icon-tools"></i>
          </div>
          <div class="service-desc">
            <h4>{{ job.title }}</h4>
            <h5><strong>{% trans "SECTOR" %}:</strong> {{ job.sector }}</h5>
            <p><strong>{% trans "CATEGORIA" %}:</strong> {{ job.category }}</p>
            <p><strong>{% trans "COUNTRY" %}: </strong>{{ job.country }}</p>
            {% if job.country == 'AR' %}
            <p><strong>Ciudad: </strong>{{ job.city }}</p>
            <p><strong>Provincia: </strong>{{ job.province_name }}</p>
            {% elif job.country == 'IT' %}
            <p><strong>Regione: </strong>{{ job.region_it }}</p>
            <p><strong>Provincia: </strong>{{ job.provincia_it }}</p>
            <p><strong>Comune: </strong>{{ job.comuna_it }}</p>
            {% endif %}
            <p><strong>{% trans "FECHA_VENCIMIENTO" %}:</strong> {{ job.expiration_date }}</p>
            <p><strong>{% trans "ADRESS" %}:</strong> {{ job.address }}</p>
            <p><strong>{% trans "DESCRIP_JOB" %}:</strong> {{ job.descripcion }}</p>
            {% if request.user.is_staff or request.user.is_superuser %}
            <form action="{% url 'delete_job_post' job.id %}" method="post" class="d-inline">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('¿Estás seguro de que deseas eliminar esta publicación?');">
                  <i class="bi bi-trash"></i>
              </button>
          </form>
          {% endif %}

            {% if job.expiration_date|date:"Y-m-d" < today %}
            <!-- Si la fecha de vencimiento es anterior a la fecha actual, muestra el botón de vencido -->
            <button class="btn btn-danger">Publicación Vencida</button>
          {% else %}
            {% if request.user.is_authenticated and request.user.userprofile %}
                {% if is_applied %}
                    <button class="btn btn-success" disabled>Ya está postulado</button>
                {% else %}
                    <form action="{% url 'apply_for_job' job.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">{% trans "POSTULARSE" %}</button>
                    </form>
                {% endif %}
                   
            {% endif %}  <!-- Cierra el bloque if aquí -->
            {% endif %}  <!-- Cierra el bloque if aquí -->
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


{% endblock %}